# Generated by Django 2.1.7 on 2019-02-24 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_auto_20190224_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='created',
            field=models.DateField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
    ]
