# Generated by Django 2.1.7 on 2019-02-25 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0004_comment_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='ratings',
            field=models.TextField(blank=True, null=True),
        ),
    ]
